03_script
git-svn-id: svn://svn.debian.org/debburn/nonameyet/trunk@31 a95a6be8-091b-0410-adaf-d31e6857962f

diff --git a/cdda2wav/cdda2mp3 b/cdda2wav/cdda2mp3
--- a/cdda2wav/cdda2mp3
+++ b/cdda2wav/cdda2mp3
@@ -14,18 +14,34 @@
 
 # specify the sampling program and its options
 # do not specify the track option here!
-CDDA2WAV=cdda2wav
-CDDA2WAV_OPTS='-H -P0 -q'
+CDDA2WAV=${CDDA2WAV:-cdda2wav}
+CDDA2WAV_OPTS=${CDDA2WAV_OPTS:-'-H -P0 -q'}
 
 # for normal use, comment out the next line
 #DEBUG='-d1'
 
 # the post processor is fed through a pipe to avoid space waste
 # specify the post processing program and its options
-MP_CODER=lame
-#MP_OPTIONS=''
+MP_CODER=${MP_CODER:-lame}
+MP_OPTIONS=${MP_OPTIONS:-''}
+
+$MP_CODER -h >/dev/null 2>&1
+if [ $? != 0 ] ; then
+   echo "Encoder not found. Install one first!"
+   exit 1
+fi
+
+if [ "$CDDADEVICE" = "" ]
+then
+  CDDA_DEVICE=/dev/cdrom
+  export CDDA_DEVICE
+fi
 
 FILEPREFIX=${1:-audiotrack}
+
+if [ -e /etc/default/cdda2mp3 ]; then
+	. /etc/default/cdda2mp3
+fi
 
 TRACK=1
 while :
