Another obvious scripting error, that code would never stop on cdda2wav failure but the whole stop mechanism depends on cdda2wav error code
git-svn-id: svn://svn.debian.org/debburn/nonameyet/trunk@116 a95a6be8-091b-0410-adaf-d31e6857962f

diff --git a/cdda2wav/cdda2mp3 b/cdda2wav/cdda2mp3
--- a/cdda2wav/cdda2mp3
+++ b/cdda2wav/cdda2mp3
@@ -40,21 +40,25 @@ if [ -e /etc/default/cdda2mp3 ]; then
 	. /etc/default/cdda2mp3
 fi
 
-TRACK=1
-while :
-do
+LIST="$($CDDA2WAV -v trackid -t -1 2>&1|grep T:|cut -f1 -d.|cut -f2 -d:)"
+if [ -z "$LIST" ] ; then
+   echo "ERROR: No audio tracks detected"
+   exit 1
+else
+   echo Found `echo $LIST | wc -w` tracks in $CDDA_DEVICE, encoding with $MP_CODER.
+   echo Cancel with Ctrl-C, watch out for error messages.
+fi
+
+for TRACK in $LIST ; do
+   echo Start ripping Track Nr. $TRACK
   $CDDA2WAV $CDDA2WAV_OPTS -t$TRACK $DEBUG - | \
 #  echo n | $MP_CODER $NPIPE $FILEPREFIX$TRACK.mp3 $MP_OPTIONS 
   $MP_CODER $MP_OPTIONS - $FILEPREFIX$TRACK.mp3 
-
   # check result code
   RES=$?
-  if [ $RES = 0 ] ; then
-    echo File $FILEPREFIX$TRACK.mp3 finished successfully.
-  else
-    echo File $FILEPREFIX$TRACK.mp3 failed \(result $RES\). Aborted. >&2
+  if [ $RES != 0 ] ; then
+    echo File $NAME failed \(result $RES\). Aborted. >&2
     break
   fi
-  TRACK=`echo $(($TRACK+1))`
 done
 
diff --git a/cdda2wav/cdda2ogg b/cdda2wav/cdda2ogg
--- a/cdda2wav/cdda2ogg
+++ b/cdda2wav/cdda2ogg
@@ -41,18 +41,24 @@ if [ -e /etc/default/cdda2ogg ]; then
 	. /etc/default/cdda2ogg
 fi
 
-TRACK=1
-while :
-do
+LIST="$($CDDA2WAV -v trackid -t -1 2>&1|grep T:|cut -f1 -d.|cut -f2 -d:)"
+if [ -z "$LIST" ] ; then
+   echo "ERROR: No audio tracks detected"
+   exit 1
+else
+   echo Found `echo $LIST | wc -w` tracks in $CDDA_DEVICE, encoding with $MP_CODER.
+   echo Cancel with Ctrl-C, watch out for error messages.
+fi
+
+for TRACK in $LIST ; do
+   echo Start ripping Track Nr. $TRACK
    NAME=`printf "%02d" $TRACK`-$FILEPREFIX.ogg
   $CDDA2WAV $CDDA2WAV_OPTS -t$TRACK $DEBUG - | \
   $MP_CODER $MP_OPTIONS - > $NAME 
 
   # check result code
   RES=$?
-  if [ $RES = 0 ] ; then
-    echo File $NAME finished successfully.
-  else
+  if [ $RES != 0 ] ; then
     echo File $NAME failed \(result $RES\). Aborted. >&2
     break
   fi
